### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by acorpuz101** [Johni0702/mumble-web-proxy#27] opened 2021-03-03 23:14 UTC
I have a local mumble server. It has no password and I'm able to connect to it with both the desktop and an android client.

When trying to set up the web client with mumble-web-proxy, I get an "invalid token" error.

`ClientConnection(Protocol("invalid token"))`

Is there additional configuration that I may be missing?

**Comment by Johni0702** [comment] 2021-03-04 08:21
Duplicate of #18

**Closed as completed by Johni0702** 2021-03-04 08:21 UTC
